// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block1': string;
  'block2': string;
  'feedback-button': string;
  'feedback-form': string;
  'feedback-text': string;
  'feedback-type': string;
  'float-right': string;
  'nav-arrow': string;
  'tutorial': string;
  'tutorial-image': string;
  'tutorial-nav': string;
  'tutorial-nav-index': string;
  'tutorial-window': string;
}
export const cssExports: CssExports;
export default cssExports;
